### ISSUE TITLE
Need help using track_analysis app

### ISSUE THREAD

**Issue by juneho27** [andrewx101/track_analysis#1]
I hope my email found you well, and I am writing here in case it didn't.

I have tried running with your example, 'tr_example.mat', as well as my own, 'w3mr2_linked_tr.mat'. Both encounter errors and do not display anything on the plots, with different error messages. I have attached the .mat files and .txt files containing the error messages.
[error_tr_example.txt](https://github.com/andrewx101/track_analysis/files/10164883/error_tr_example.txt)
[error_w3mr2_linked_tr.txt](https://github.com/andrewx101/track_analysis/files/10164884/error_w3mr2_linked_tr.txt)
[track_analysis files.zip](https://github.com/andrewx101/track_analysis/files/10164886/track_analysis.files.zip)

**Comment by andrewx101** [comment]
I received and replied to your mail. 

The app needs the 'smooth' function in the Curve Fitting Toolbox.

The older version "v2.04" does not expect (and will raise errors upon) tracks with only one position, because one cannot calculate displacement out of one position. The newer version "v.2.05" handles this issue by filtering out single-point tracks before calculation so it will process thoroughly the w3mr2_linked_tr data without error messages, as I have tested in my environment.
